development:
  adapter: postgresql
  encoding: unicode
  database: myblog_dev
  pool: 5
  host: localhost
  username: wayne
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myblog-test
  pool: 5
  host: localhost
  username: wayne
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: myblog-prod
  pool: 5
  host: localhost
  username: wayne
  password: