# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e5a740bc50271d84a15b08bd0951e28ad23a11fb66f64f887a66d8d5dd4f1580990fc11fddb3c5464dd36880639c06fe22692e17538425a3d10ecf48022c25
  


test:
  secret_key_base: 093b0ce69aea05322e5497babc7df70a480e306bec9937bceddb56bbc2536f1e487f864adf99ea43c4dc42f9d315d6b705f575abdbe07eb906cb094eb8b45a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  

